import { ArrowRight, Check, Play, Sparkles } from "lucide-react";
import Link from "next/link";
import { categories, products } from "@/src/data/site-content";
import { SectionHeading } from "./section-heading";

export function HomePage() {
  return <main>
    <section className="hero"><div className="hero-content"><p className="eyebrow light">A little care goes a long way</p><h1>Everyday essentials,<br /><em>beautifully made.</em></h1><p>From the first light of morning to the last quiet moment at night, discover care made for the life you live.</p><div className="hero-actions"><Link className="button button-light" href="#products">Explore our products <ArrowRight size={17}/></Link><Link className="text-link light" href="#about"><Play size={15} fill="currentColor"/> Our story</Link></div></div><div className="hero-art"><div className="hero-orb orb-one"/><div className="hero-orb orb-two"/><div className="hero-bottle"><span>manola</span><small>silk bloom<br/>body lotion</small></div><div className="hero-note">Made for your<br/><b>everyday ritual</b></div></div></section>
    <section className="trust-strip"><span>Feel-good formulations</span><i/><span>Kind to skin</span><i/><span>Made in Bangladesh</span><i/><span>Thoughtful everyday care</span></section>
    <section id="products" className="content-section categories-section"><SectionHeading eyebrow="Find your everyday" title="Care for every corner of life">Whether it&apos;s a moment for yourself or a home that feels like you, our products bring a little more joy to the routine.</SectionHeading><div className="category-grid">{categories.map((category) => <Link href="#" className={`category-card ${category.color}`} key={category.title}><img src={category.image} alt=""/><div className="category-overlay"/><div><p>{category.description}</p><h3>{category.title}</h3><span>Explore <ArrowRight size={16}/></span></div></Link>)}</div></section>
    <section id="about" className="story-section"><div className="story-image"><img src="https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=1100&q=85" alt="A flower and fragrance bottle"/><div className="story-stamp"><Sparkles size={20}/><span>Made with<br/>a little magic</span></div></div><div className="story-copy"><SectionHeading eyebrow="Our point of view" title="Care should feel like a small celebration.">We believe everyday products can be effective, thoughtful and a delight to use. That&apos;s why we put the same care into every detail—from the ingredients we choose to the moments they create.</SectionHeading><Link className="text-link" href="#">Meet Manola <ArrowRight size={17}/></Link></div></section>
    <section className="content-section featured"><div className="featured-heading"><SectionHeading eyebrow="The favourites" title="Loved in every routine">Discover the products people reach for, again and again.</SectionHeading><Link className="text-link" href="#">View all products <ArrowRight size={17}/></Link></div><div className="product-grid">{products.map((product, index) => <article className="product-card" key={product.name}><div className={`product-image image-${index}`}><img src={product.image} alt={product.name}/><button aria-label={`Add ${product.name} to wishlist`}>♡</button></div><p>{product.category}</p><h3>{product.name}</h3><Link href="#">Discover <ArrowRight size={15}/></Link></article>)}</div></section>
    <section id="impact" className="impact-section"><div><p className="eyebrow light">Less is more</p><h2>Made with more thought.<br/><em>Made for tomorrow.</em></h2><p>Better choices, lighter footprints and a commitment to creating products that care for more than just today.</p><Link className="button button-light" href="#">Our commitment <ArrowRight size={17}/></Link></div><div className="impact-points"><div><Check size={17}/><span>Responsible sourcing</span></div><div><Check size={17}/><span>Recyclable packaging</span></div><div><Check size={17}/><span>Kind formulations</span></div></div></section>
  </main>;
}
